version: '3.1'

services:

  app-api-geteway:
    image: '52bd052a251a'
    container_name: spring_application_api_geteway
    ports:
      - '127.0.0.1:8091:8091'

  app-clientservice:
    image: 'c7fbbd3af7a1'
    container_name: spring_application_clientservice
    ports:
      - '127.0.0.1:8189:8189'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  app-billservice:
    image: 'e6692c05cb52'
    container_name: spring_application_billservice
    ports:
      - '127.0.0.1:8190:8190'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/billservicelab_db
      - DB_PASSWORD=password
    depends_on:
      - db

  app-userservice:
    image: 'e32f4d544e04'
    container_name: spring_application_userservice
    ports:
      - '127.0.0.1:8191:8191'
    environment:
      - DB_USER=pavel
      - DB_URL=jdbc:postgresql://db:5432/userservice_db
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=pavel
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: